openapi: "3.0.3"
info:
  title: "PSBAPP WFPNTS API"
  version: "2021-05-27"

paths:
  /p/{placeId}:
    parameters:
      - in: path
        schema:
          type: string
        name: placeId
        required: true
    get:
      tags: [End User]
      description: Ottieni informazioni su un luogo
      responses:
        200:
          description: Informazioni sul luogo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceInfo"
        444:
          description: Luogo non esistente

  ##### SEARCH API
  /search/p:
    get:
      tags: [End User, Search]
      parameters:
        - name: q
          in: query
          description: >-
            The text for full text search on all fields
          required: false
          schema:
            type: string
        - name: near
          in: query
          description: >-
            Latitude and longitude for the search
          required: false
          schema:
            type: string
            example: 45.1234,11.3749
            pattern: '\d{1,2}(.\d*)\,\d{1,2}(.\d*)'
      summary: Search places
      description: >-
        At least one of the 'q' or the 'near' parameters is required
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlaceList"

components:
  schemas:
    PlaceList:
      type: object
      properties:
        places:
          type: array
          items:
            $ref: "#/components/schemas/PlaceInfo"
    PlaceInfo:
      type: object
      properties:
        placeId:
          type: string
          example: clzd-th
        building:
          type: string
          example: Scuola Primaria
        operator:
          type: string
          example: Pasubio Tecnologie
        address:
          type: string
          example: Via Falgare
        city:
          type: string
          example: Thiene
        province:
          type: string
          example: VI
        region:
          type: string
          example: Veneto
        lat:
          type: string
          example: 45.50593824
        lon:
          type: string
          example: 12.293843284
        searchable:
          type: boolean
        accessPoints:
          type: array
          items:
            $ref: "#/components/schemas/AccessPoint"
    AccessPoint:
      type: object
      properties:
        ideCode:
          type: string
          example: SCH-E-CIP-01
        installationDate:
          type: string
          example: "2016"
        frequencies:
          type: string
          example: 2.4 ghz e 5 ghz

tags:
  - name: End User
    description: Chiamate utilizzate dall'end user, non sono autenticate.
  - name: Search
    description: Chiamate per cercare i luoghi
